# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
# https://github.com/marketplace/actions/check-code-formatting-using-gofmt

name: Go

on: [push, pull_request]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Check formatting
      uses: Jerome1337/gofmt-action@v1.0.5
      with:
        gofmt-path: '.'
        gofmt-flags: '-l -d'

  build-and-test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  build-docker-images:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker compose build
  
